# Generated by Django 3.2.15 on 2022-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip4addr', models.GenericIPAddressField()),
                ('sysName', models.CharField(max_length=255)),
                ('sysDescr', models.CharField(max_length=255)),
                ('sysLocation', models.CharField(max_length=255)),
                ('tier', models.CharField(max_length=255)),
                ('building_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('last_refresh', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Distribution', 'Distribution'), ('Building', 'Building')], max_length=32)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('switch_count', models.IntegerField()),
                ('ap_count', models.IntegerField()),
                ('ups_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('percent_down', models.DecimalField(decimal_places=3, max_digits=3)),
                ('last_event', models.DateTimeField()),
                ('trend', models.CharField(max_length=255)),
                ('incident', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unresponsive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('device_added', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('ip4addr', models.GenericIPAddressField()),
                ('last_refresh', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
