# Generated by Django 3.2.15 on 2022-08-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip4addr'], name='akips_devic_ip4addr_0bbcf4_idx'),
        ),
    ]
