# Generated by Django 3.2.15 on 2022-09-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0002_device_akips_devic_ip4addr_0bbcf4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unreachable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('device_added', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('ip4addr', models.GenericIPAddressField()),
                ('last_refresh', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akips.device')),
            ],
            options={
                'ordering': ['ip4addr'],
            },
        ),
    ]
