# Generated by Django 3.2.15 on 2022-09-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0003_unreachable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unresponsive',
        ),
    ]
