# Generated by Django 3.2.15 on 2022-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0004_delete_unresponsive'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hierarcy',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
