# Generated by Django 3.2.15 on 2022-09-06 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0005_device_hierarcy'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='first_event',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 13, 14, 44, 550118, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
