# Generated by Django 3.2.15 on 2022-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0006_summary_first_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='ap_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='incident',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='percent_down',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='summary',
            name='switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='ups_count',
            field=models.IntegerField(default=0),
        ),
    ]
