# Generated by Django 3.2.15 on 2022-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0008_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='device',
            field=models.ManyToManyField(related_name='devices', to='akips.Device'),
        ),
    ]
