# Generated by Django 3.2.15 on 2022-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0009_alter_group_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
