# Generated by Django 3.2.15 on 2022-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0011_alter_group_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
