# Generated by Django 3.2.15 on 2022-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0012_auto_20220907_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='building_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='hierarcy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='sysDescr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='sysLocation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='sysName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='tier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('Distribution', 'Distribution'), ('Building', 'Building'), ('Critical', 'Critical')], max_length=32),
        ),
    ]
