# Generated by Django 3.2.15 on 2022-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0013_auto_20220907_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
