# Generated by Django 3.2.15 on 2022-09-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0015_summary_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akips.device'),
        ),
    ]
