# Generated by Django 3.2.15 on 2022-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0016_summary_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='unreachables',
            field=models.ManyToManyField(to='akips.Unreachable'),
        ),
    ]
