# Generated by Django 3.2.15 on 2022-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0017_summary_unreachables'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreachable',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=32),
            preserve_default=False,
        ),
    ]
