# Generated by Django 3.2.15 on 2022-09-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0018_unreachable_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unreachable',
            options={'ordering': ['event_start']},
        ),
    ]
