# Generated by Django 3.2.15 on 2022-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0021_summary_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreachable',
            name='ip4addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
