# Generated by Django 3.2.15 on 2022-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0022_alter_unreachable_ip4addr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['type', 'name', 'first_event']},
        ),
        migrations.AlterModelOptions(
            name='unreachable',
            options={'ordering': ['device', 'event_start']},
        ),
        migrations.AlterField(
            model_name='summary',
            name='trend',
            field=models.CharField(default='New', max_length=255),
        ),
    ]
