# Generated by Django 3.2.15 on 2022-09-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0023_auto_20220916_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='percent_down',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
