# Generated by Django 3.2.15 on 2022-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0024_alter_summary_percent_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreachable',
            name='state',
        ),
        migrations.AddField(
            model_name='unreachable',
            name='ping_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=32),
        ),
        migrations.AddField(
            model_name='unreachable',
            name='snmp_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=32),
        ),
    ]
