# Generated by Django 3.2.15 on 2022-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0025_auto_20220920_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreachable',
            name='ping_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unreported', 'unreported')], default='up', max_length=32),
        ),
        migrations.AlterField(
            model_name='unreachable',
            name='snmp_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unreported', 'unreported')], default='up', max_length=32),
        ),
    ]
