# Generated by Django 3.2.15 on 2022-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0026_auto_20220920_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreachable',
            name='ping_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unreported', 'unreported')], default='unreported', max_length=32),
        ),
        migrations.AlterField(
            model_name='unreachable',
            name='snmp_state',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unreported', 'unreported')], default='unreported', max_length=32),
        ),
    ]
