# Generated by Django 3.2.15 on 2022-09-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0027_auto_20220920_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='device',
        ),
    ]
