# Generated by Django 3.2.15 on 2022-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0028_remove_summary_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='tier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
