# Generated by Django 3.2.15 on 2022-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0029_summary_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='tier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
