# Generated by Django 3.2.15 on 2022-09-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0031_alter_summary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.DateTimeField()),
                ('ipaddr', models.GenericIPAddressField()),
                ('trap_oid', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
                ('oids', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akips.device')),
            ],
        ),
    ]
