# Generated by Django 3.2.15 on 2022-09-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0032_snmptrap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookMessage',
        ),
    ]
