# Generated by Django 3.2.15 on 2022-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0033_delete_webhookmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmptrap',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snmptrap',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=32),
        ),
    ]
