# Generated by Django 3.2.15 on 2022-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0034_auto_20220921_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmptrap',
            name='incident',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
