# Generated by Django 3.2.15 on 2022-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0035_snmptrap_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('sound', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
