# Generated by Django 3.2.15 on 2022-10-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0038_auto_20220923_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='kind of alert fired', max_length=255)),
                ('tt', models.DateTimeField(help_text='epoch time of the alert')),
                ('child', models.CharField(help_text='child or interface name', max_length=255)),
                ('descr', models.CharField(help_text='child description', max_length=255)),
                ('attr', models.CharField(help_text='MIB.object', max_length=255)),
                ('alias', models.CharField(help_text='attr description', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akips.device')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('last_change', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akips.device')),
            ],
        ),
    ]
