# Generated by Django 3.2.15 on 2022-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0040_summary_ups_battery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['device']},
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['object'], name='akips_statu_object_b99fde_idx'),
        ),
    ]
