# Generated by Django 3.2.15 on 2022-10-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0041_auto_20221001_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['device'], 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['tier', '-type', 'name', 'first_event'], 'verbose_name_plural': 'summaries'},
        ),
    ]
