# Generated by Django 3.2.15 on 2022-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0042_auto_20221003_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='moving_average',
            field=models.IntegerField(default=0),
        ),
    ]
