# Generated by Django 3.2.15 on 2022-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0043_summary_moving_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='moving_average',
            field=models.FloatField(default=0),
        ),
    ]
