# Generated by Django 3.2.15 on 2022-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0044_alter_summary_moving_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='moving_avg_count',
            field=models.IntegerField(default=0),
        ),
    ]
