# Generated by Django 3.2.15 on 2022-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0047_status_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-first_event'], 'verbose_name_plural': 'summaries'},
        ),
        migrations.AlterModelOptions(
            name='unreachable',
            options={'ordering': ['event_start']},
        ),
    ]
