# Generated by Django 3.2.15 on 2022-10-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0048_auto_20221006_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snmptrap',
            options={'ordering': ['-tt']},
        ),
        migrations.AlterModelOptions(
            name='unreachable',
            options={'ordering': ['-event_start']},
        ),
    ]
