# Generated by Django 3.2.15 on 2022-10-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0049_auto_20221006_1305'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='akips_devic_ip4addr_0bbcf4_idx',
        ),
    ]
