# Generated by Django 3.2.15 on 2022-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0051_device_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('Distribution', 'Distribution'), ('Building', 'Building'), ('Critical', 'Critical'), ('Speciality', 'Speciality')], max_length=32),
        ),
    ]
