# Generated by Django 3.2.15 on 2022-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0052_alter_summary_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusAlert',
        ),
    ]
