# Generated by Django 3.2.15 on 2022-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0053_delete_statusalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmptrap',
            name='dup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snmptrap',
            name='dup_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
