# Generated by Django 3.2.15 on 2022-10-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0054_auto_20221014_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAlert',
        ),
    ]
