# Generated by Django 3.2.15 on 2022-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0055_delete_useralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='batteries',
            field=models.ManyToManyField(to='akips.Status'),
        ),
    ]
