# Generated by Django 3.2.15 on 2022-10-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0056_summary_batteries'),
    ]

    operations = [
        migrations.CreateModel(
            name='HibernateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Auto', 'Auto'), ('Time', 'Time')], max_length=32)),
                ('scheduled', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=32)),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akips.device')),
            ],
        ),
    ]
