# Generated by Django 3.2.15 on 2022-10-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0057_hibernaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hibernaterequest',
            name='type',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Time', 'Time'), ('Manual', 'Manual')], max_length=32),
        ),
    ]
