# Generated by Django 3.2.15 on 2022-10-21 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0058_alter_hibernaterequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='last_refresh',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time the summmary data was refreshed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='first_event',
            field=models.DateTimeField(help_text='First up/down event in the summary time period'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_event',
            field=models.DateTimeField(help_text='Last up/down event in the summary time period'),
        ),
    ]
