# Generated by Django 3.2.15 on 2022-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0059_auto_20221021_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='batteries',
            field=models.ManyToManyField(blank=True, to='akips.Status'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='unreachables',
            field=models.ManyToManyField(blank=True, to='akips.Unreachable'),
        ),
    ]
