# Generated by Django 3.2.15 on 2022-11-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0062_auto_20221028_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SNMPTrap',
            new_name='Trap',
        ),
    ]
