# Generated by Django 3.2.15 on 2022-11-04 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0063_rename_snmptrap_trap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hibernaterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hibernaterequest',
            name='created_by',
            field=models.CharField(default='wew', max_length=32),
            preserve_default=False,
        ),
    ]
