# Generated by Django 3.2.15 on 2022-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0064_auto_20221104_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='ack_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='trap',
            name='ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trap',
            name='ack_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
