# Generated by Django 3.2.15 on 2022-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0065_auto_20221104_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='trap',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trap',
            name='cleared_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
