# Generated by Django 3.2.15 on 2023-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0066_auto_20221110_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='inventory_url',
            field=models.URLField(blank=True),
        ),
    ]
