# Generated by Django 3.2.15 on 2023-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0067_device_inventory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
