# Generated by Django 3.2.15 on 2023-02-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0068_alter_device_inventory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreachable',
            name='device_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unreachable',
            name='index',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
