# Generated by Django 3.2.15 on 2023-02-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0069_auto_20230228_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='device_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='index',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='ip4addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
