# Generated by Django 3.2.15 on 2023-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0070_auto_20230228_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('sys_id', models.UUIDField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
