# Generated by Django 3.2.15 on 2023-03-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0071_servicenowincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='sn_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akips.servicenowincident'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_refresh',
            field=models.DateTimeField(auto_now_add=True, help_text='Last time the summary data was refreshed'),
        ),
    ]
