# Generated by Django 3.2.15 on 2023-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0073_trap_sn_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowincident',
            name='sys_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
