# Generated by Django 3.2.15 on 2023-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0075_servicenowincident_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
