# Generated by Django 3.2.20 on 2023-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0076_profile_alert_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('Distribution', 'Distribution'), ('Building', 'Building'), ('Critical', 'Critical'), ('Specialty', 'Specialty')], max_length=32),
        ),
    ]
