# Generated by Django 3.2.20 on 2023-07-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0077_alter_summary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='hierarcy',
            new_name='hierarchy',
        ),
    ]
