# Generated by Django 3.2.22 on 2024-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0078_rename_hierarcy_device_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='oids',
            field=models.CharField(max_length=2048),
        ),
    ]
