# Generated by Django 4.2.16 on 2024-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0079_alter_trap_oids'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
