# Generated by Django 4.2.16 on 2024-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0081_tdxincident_summary_tdx_incident_trap_tdx_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdxincident',
            name='number',
            field=models.IntegerField(),
        ),
    ]
