# Generated by Django 4.2.16 on 2024-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0082_alter_tdxincident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='tdx_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trap',
            name='tdx_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
