# Generated by Django 4.2.16 on 2024-10-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0083_alter_summary_tdx_incident_alter_trap_tdx_incident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TDXIncident',
        ),
    ]
