# Generated by Django 4.2.29 on 2026-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0087_akipsconfiguration_alter_inventoryconfiguration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akipsconfiguration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryconfiguration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tdxconfiguration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
