# Generated by Django 4.2.29 on 2026-04-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akips', '0088_alter_akipsconfiguration_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=12)),
                ('hashed_key', models.CharField(max_length=255)),
                ('allowed_endpoints', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_access_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API access key',
                'verbose_name_plural': 'API access keys',
                'ordering': ['name'],
            },
        ),
    ]