# Generated by Django 4.2.16 on 2026-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akips', '0089_apiaccesskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesskey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]